openapi: 3.0.3
info:
  title: East Lancashire Table Tennis League
  description: Table tennis league website
  version: 0.0.0
  contact:
    name: Martin Wyatt
    email: martin.wyatt@gmail.com
servers:
  - url: http://localhost
    description: Dev
paths:
  /:
    get:
      summary: Homepage
      tags:
        - Frontend
      responses:
        200:
          description: Homepage loads
          content:
            text/html:
              schema:
                type: string
#  /api/admin/fixture/{id}:
#    post:
#      summary: Submit a completed fixture
#      tags:
#        - API
#      requestBody:
#        content:
#          application/json:
#            schema:
#              type: object
#              properties:
#                playerArrangement:
#                  type: array
#      responses:
#        200:
#
